import { Check, Copy, KeyRound, RefreshCw } from 'lucide-react'
import type { OTP } from '../types'

function formatTime(seconds: number) { return `00:${String(seconds).padStart(2, '0')}` }

export function OtpCard({ otp, copied, loading, onCopy, onGenerate }: { otp: OTP; copied: boolean; loading: boolean; onCopy: () => void; onGenerate: () => void }) {
  const expired = otp.status === 'expired'
  return <section className="rounded-2xl border border-[#dfe8dc] bg-white p-6 shadow-[0_10px_28px_rgba(35,75,53,0.06)] dark:border-[#35504a] dark:bg-[#1b3832] sm:p-7"><div className="flex items-center justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[0.13em] text-[#789089]">Demo OTP</p><h2 className="mt-1 text-lg font-bold text-[#17332e] dark:text-[#edf8ea]">One-time passcode</h2></div><span className="grid size-10 place-items-center rounded-xl bg-[#f1f8e8] text-[#789e35] dark:bg-[#294d42]" aria-hidden="true"><KeyRound size={19} /></span></div><div className={`mt-6 rounded-xl border px-4 py-5 text-center ${expired ? 'border-[#f1d5d0] bg-[#fff8f7]' : 'border-[#e1edda] bg-[#f8fcf5] dark:border-[#35504a] dark:bg-[#203f37]'}`}><p className={`font-mono text-3xl font-bold tracking-[0.28em] ${expired ? 'text-[#b26a5f] line-through' : 'text-[#17332e] dark:text-[#eaf5e9]'}`}>{expired ? '------' : otp.code}</p><p className={`mt-2 text-xs font-semibold ${expired ? 'text-[#b26a5f]' : 'text-[#789089]'}`}>{expired ? 'OTP Expired' : `OTP expires in ${formatTime(otp.expiresIn)}`}</p></div><div className="mt-4 flex gap-2"><button type="button" onClick={onCopy} disabled={expired} className="flex flex-1 items-center justify-center gap-2 rounded-lg border border-[#dfe8dc] px-3 py-2.5 text-xs font-bold text-[#49635b] transition hover:border-[#aec78b] disabled:cursor-not-allowed disabled:opacity-50 dark:border-[#426158] dark:text-[#d7e9d5]">{copied ? <Check size={14} /> : <Copy size={14} />}{copied ? 'Copied' : 'Copy OTP'}</button><button type="button" onClick={onGenerate} disabled={loading} className="flex flex-1 items-center justify-center gap-2 rounded-lg bg-[#d4f56d] px-3 py-2.5 text-xs font-bold text-[#17332e] transition hover:bg-[#c6eb54] disabled:cursor-wait disabled:opacity-70">{loading ? 'Generating OTP...' : <><RefreshCw size={14} /> {expired ? 'Generate New OTP' : 'Generate OTP'}</>}</button></div><p className="mt-4 text-center text-[11px] leading-4 text-[#8a9b95]">This OTP is for demonstration purposes only.</p></section>
}
